// <auto-generated />
using CRUDTechTest.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDTechTest.Migrations
{
    [DbContext(typeof(TechTestTapebringContext))]
    partial class TechTestTapebringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUDTechTest.Entities.Kendaraan", b =>
                {
                    b.Property<string>("NomorRegistrasi")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("BahanBakar")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("KapasitasSilinder")
                        .HasColumnType("int");

                    b.Property<string>("MerkKendaraan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NamaPemilik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TahunPembuatan")
                        .HasColumnType("int");

                    b.Property<string>("WarnaKendaraan")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NomorRegistrasi");

                    b.HasIndex("NomorRegistrasi")
                        .IsUnique();

                    b.ToTable("Kendaraan");

                    b.HasData(
                        new
                        {
                            NomorRegistrasi = "B1234ABC",
                            Alamat = "Jl. Sudirman No. 123, Pemalang",
                            BahanBakar = "Bensin",
                            KapasitasSilinder = 2000,
                            MerkKendaraan = "Toyota",
                            NamaPemilik = "Ahmad Kurniawan",
                            TahunPembuatan = 2020,
                            WarnaKendaraan = "Putih"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
